import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const root = path.resolve(__dirname, '../..')

const supplyApiPath = path.join(root, 'frontend/src/api/supplySourceAPI.ts')
const routerPath = path.join(root, 'frontend/src/router/index.ts')
const layoutPath = path.join(root, 'frontend/src/components/MainLayout.vue')
const roleManagementPath = path.join(root, 'frontend/src/views/settings/role-management/Index.vue')
const productCollectionPath = path.join(root, 'frontend/src/views/source-collection/product-collection/Index.vue')
const supplyManagementPath = path.join(root, 'frontend/src/views/source-collection/supply-management/Index.vue')

assert.ok(fs.existsSync(supplyApiPath), 'supplySourceAPI.ts should exist')

const supplyApi = fs.readFileSync(supplyApiPath, 'utf8')
const router = fs.readFileSync(routerPath, 'utf8')
const layout = fs.readFileSync(layoutPath, 'utf8')
const roleManagement = fs.readFileSync(roleManagementPath, 'utf8')
const productCollection = fs.readFileSync(productCollectionPath, 'utf8')

assert.match(supplyApi, /export interface SupplySource/, 'frontend supply API should expose SupplySource type')
assert.match(supplyApi, /getSupplySourceItems/, 'frontend supply API should list supply sources')
assert.match(supplyApi, /previewSupplySourceUrl/, 'frontend supply API should preview URL')
assert.match(supplyApi, /importSupplySourceUrl/, 'frontend supply API should import URL')
assert.match(supplyApi, /updateSupplySourceItem/, 'frontend supply API should update source')
assert.match(supplyApi, /deleteSupplySourceItem/, 'frontend supply API should delete source')
assert.match(supplyApi, /\/supply-sources/, 'frontend supply API should call dedicated supply-sources endpoint')
assert.doesNotMatch(supplyApi, /\/product-supply\/sources/, 'supply management page should not use product-library source endpoint')

assert.match(router, /path:\s*'\/source-collection'[\s\S]*redirect:\s*'\/source-collection\/product-collection'/, 'legacy source collection route should redirect to product collection')
assert.match(router, /path:\s*'\/source-collection\/product-collection'/, 'router should expose product collection child route')
assert.match(router, /path:\s*'\/source-collection\/supply-management'/, 'router should expose supply management child route')
assert.match(router, /menuKey:\s*'source-collection\/product-collection'/, 'product collection route should use child menu key')
assert.match(router, /menuKey:\s*'source-collection\/supply-management'/, 'supply management route should use child menu key')
assert.match(router, /hasLegacySourceCollectionAccess/, 'router guard should keep legacy source-collection permission compatibility')

assert.match(layout, /sourceCollectionSubmenuOpen/, 'layout should track source collection submenu state')
assert.match(layout, /toggleSourceCollectionSubmenu/, 'layout should toggle source collection submenu')
assert.match(layout, /source-collection\/product-collection/, 'layout should link to product collection')
assert.match(layout, /source-collection\/supply-management/, 'layout should link to supply management')
assert.match(layout, /商品采集/, 'layout should label product collection submenu')
assert.match(layout, /货源管理/, 'layout should label supply management submenu')

assert.match(roleManagement, /source-collection\/product-collection/, 'role permissions should include product collection leaf')
assert.match(roleManagement, /source-collection\/supply-management/, 'role permissions should include supply management leaf')
assert.match(roleManagement, /normalizeLegacySourceCollectionPermissions/, 'role permissions should normalize legacy source-collection permission')

assert.match(productCollection, /createProductSupplyItem/, 'product collection should keep existing product supply creation flow')
assert.match(productCollection, /alibabaAPI\.searchSimilar/, 'product collection should keep search similar flow')
assert.match(productCollection, /alibabaAPI\.searchByImage/, 'product collection should keep image search flow')

assert.ok(fs.existsSync(supplyManagementPath), 'supply management page should exist')
const supplyManagement = fs.readFileSync(supplyManagementPath, 'utf8')
assert.match(supplyManagement, /添加货源/, 'supply management page should support adding sources')
assert.doesNotMatch(supplyManagement, /<AppPageHeader[\s\S]*?title="货源管理"/, 'supply management content should not render a page title inside the panel')
assert.match(supplyManagement, /class="supply-toolbar"[\s\S]*?class="supply-search-group"[\s\S]*?class="input-search header-search-input"[\s\S]*?class="btn-create"/, 'supply management toolbar should put search on the left and create action on the right')
assert.doesNotMatch(supplyManagement, /subtitle="管理搜同款、搜同类和1688链接保存的货源商品"/, 'supply management header should not render the old explanatory subtitle')
assert.doesNotMatch(supplyManagement, /h-\[100px\][\s\S]*?border-b border-slate-100[\s\S]*?handleSearch/, 'supply management should not keep a dedicated search bar row under the header')
assert.match(supplyManagement, /getSupplySourceItems/, 'supply management page should list sources through dedicated API')
assert.match(supplyManagement, /previewSupplySourceUrl/, 'supply management page should preview 1688 links')
assert.match(supplyManagement, /importSupplySourceUrl/, 'supply management page should import 1688 links')
assert.match(supplyManagement, /deleteSupplySourceItem/, 'supply management page should delete sources')
assert.match(supplyManagement, /source-title-link/, 'supply management product title should be the 1688 detail link')
assert.match(supplyManagement, /startImageCarousel/, 'supply management image should start carousel on hover')
assert.match(supplyManagement, /stopImageCarousel/, 'supply management image should stop carousel when hover ends')
assert.match(supplyManagement, /getCarouselStripStyle/, 'supply management should choose current carousel image')
assert.doesNotMatch(supplyManagement, /YX_SCORE_LEVEL/, 'supply management card should hide raw yx score level')
assert.match(supplyManagement, /综合/, 'supply management should show quality score summary')
assert.match(supplyManagement, /商品/, 'supply management should show product score label')
assert.match(supplyManagement, /物流/, 'supply management should show logistics score label')
assert.match(supplyManagement, /代发/, 'supply management should show consign price')
assert.doesNotMatch(supplyManagement, /supplier-line/, 'supply management card should hide supplier and city line')
assert.match(supplyManagement, /grid-template-columns:\s*repeat\(auto-fill,\s*minmax\(360px,\s*1fr\)\)/, 'supply management cards should be compact enough for multiple columns')
assert.match(supplyManagement, /\.source-score-row\s*\{[\s\S]*?flex-wrap:\s*nowrap/, 'supply management score chips should stay on one line')
assert.match(supplyManagement, /\.supply-source-actions\s*\{[\s\S]*?position:\s*absolute/, 'supply management delete action should not reserve a grid column')
assert.doesNotMatch(supplyManagement, /grid-template-columns:\s*\d+px minmax\(0,\s*1fr\) \d+px/, 'supply management card should not reserve a dedicated action column')
assert.match(supplyManagement, /\.supply-toolbar\s*\{[\s\S]*?height:\s*100px/, 'supply management toolbar should match the 100px search area height')
assert.match(supplyManagement, /\.header-search-input\s*\{[\s\S]*?width:\s*320px/, 'supply management search input should be compact')
assert.doesNotMatch(supplyManagement, /\.supply-toolbar\s*:deep\(\.btn-create\)/, 'supply management create button should use the shared btn-create dimensions')
assert.match(supplyManagement, /\.supply-source-info\s*\{[\s\S]*?justify-content:\s*center/, 'supply management card text area should be vertically centered')
assert.match(supplyManagement, /:disabled="isSourceDeleteDisabled\(source\)"/, 'bound supply source cards should disable delete button')
assert.match(supplyManagement, /boundProductCount/, 'supply management should read bound product count')
assert.match(supplyManagement, /hasBoundProducts/, 'supply management should read bound product status')
assert.match(supplyManagement, /source-preview-score-row/, 'supply source preview should show score chips like list cards')
assert.match(supplyManagement, /source-preview-consign-price/, 'supply source preview should show consign price like list cards')
assert.doesNotMatch(supplyManagement, /\.source-preview-box\s*\{[\s\S]*?min-height:\s*190px/, 'supply source preview should not reserve blank fixed height')
assert.doesNotMatch(supplyManagement, /\.source-preview-box\s*\{[\s\S]*?border-bottom:/, 'supply source preview should not draw an extra bottom line')
assert.doesNotMatch(supplyManagement, /source-preview-meta/, 'supply source preview should not show supplier/id/location meta row')
assert.doesNotMatch(supplyManagement, /<template #prefix>[\s\S]*?<el-icon><Search \/><\/el-icon>[\s\S]*?<\/template>[\s\S]*?@keyup\.enter="handleSearch"/, 'supply management search input should not add a duplicate prefix icon')
assert.doesNotMatch(supplyManagement, /AppTableButton name="detail"/, 'supply management should remove detail action button')
assert.doesNotMatch(supplyManagement, /AppTableButton name="edit"/, 'supply management should remove edit action button')
assert.doesNotMatch(supplyManagement, /openEditDialog/, 'supply management should not expose edit dialog')
assert.doesNotMatch(supplyManagement, /updateSupplySourceItem/, 'supply management should not import update API when editing is disabled')

console.log('sourceManagementSplit tests passed')
