ALTER TABLE `products_supply`
  ADD COLUMN `packageLength` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `packageWidth` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `packageHeight` DOUBLE NOT NULL DEFAULT 0,
  ADD COLUMN `grossWeight` DOUBLE NOT NULL DEFAULT 0;
